### ISSUE TITLE
请问支持选择sku吗？如何修改

### ISSUE THREAD

**Issue by fanwumax** [ouromoros/secondkiller#1]
有的订单需要选择sku后才能下单，请问如何实现？
另外想问下修改数量再下单的实现方法

**Comment by ouromoros** [comment]
skuId的话在商品界面选完参数后url就会包括，至于修改数量用selenium找到那个输入框之后使用sendkey函数就行了，一般有限购所以感觉意义不大。

我这个主要是针对无法加入购物车的秒杀商品，可以加入购物车的话那就是先手动加入购物车，然后再在购物车界面下单，暂时没有实现。

**Comment by fanwumax** [comment]
感谢回答，问题解决！
